---
title: "Messer-Sealey-White-ADA-2020-vignette-assignment"
author: "BA White, BA Sealey, E Messer"
date: "5/13/2020"
output: html_document
---
## Files to Turn In: 
## 1) RMD file(1) and thus html(2) for vignette module
## 2) vignette R package (3) using 1 or more dataset and NOW 2 functions of choice 

## Vignette Assignemt Objectives:
## 1a) walk users through demonstrations of relevant analyses in module style 
## 2a) set of functions and associated function documentation appropriate to the topic you have chosen
## 2b) one or more relevant datasets (either data you have simulated or, preferably, real data), that you use in a module vignette about your chosen topic
## 2c) A vignette that walks users through relevant analyses and appropriate METADATA for your package (e.g., information on dependencies, etc.)

# Objectives
network analysis blah blah blah

# Preliminaries
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
# more libraries etc
```

# Introduce NEW dataset 
Vipers were exposed to the presence of two "simulated" predators, where a preserved specimen of an avian flying and a predator touch were exposed to individual in treatment 1 and treatment 2, respectively. Dataset includes a matrix of similarity index of vipers antipredator display.    

# Specific question
## How similar did individual vipers move their heads in response to an avian flying?
## How similar did individual vipers move their heads in response to a predator touch?
## How does viper mean centrality of similarity compare between the avian flying and predator touch treatments? 

# Background on why people use this statistical approach
# You create a similarity index using ethogram values between individuals. The ratio of antipredator behavior is divided by all the individuals antipredator behavior. 

# Analysis 


# Data Visualization
# Our prediction is that the visualization will cluster antipredator behavior in the center - lines represent the similarity by thickness. Centrality is represented by node size. 

# Statistical Approach
# Compare similarity index between an avian flying over and being touched by a predator. 

# Inferring Results 
# Individual vipers typically behaved similarly in both treatments as expected. 

# Concept Overview 

