library(tidyverse)
d <- read_csv("../Black_treatments/vip_heads20200515.csv", col_names=TRUE)
d <- select(d, -names)
head(d)
d <- as.matrix(d)
d[lower.tri(d, diag=TRUE)] <- NA
library(reshape2)
r <- setNames(melt(d), c('ind1', 'ind2', 'values'))
head(r)
r <- filter(r, !is.na(values))
summary(r)

library(visNetwork)
p <- graph_from_data_frame(r, directed = FALSE, vertices = NULL)
plot(p)
